-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users_shopspy (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  plan TEXT NOT NULL DEFAULT 'mensal' CHECK (plan IN ('mensal', 'vitalicio')),
  plan_expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  transaction_id TEXT,
  customer_name TEXT
);

-- Tabela de admins
CREATE TABLE IF NOT EXISTS admins_shopspy (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de logs de webhook
CREATE TABLE IF NOT EXISTS webhook_logs_shopspy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT,
  payload JSONB,
  processed BOOLEAN DEFAULT false,
  error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE users_shopspy ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins_shopspy ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_logs_shopspy ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can read own record" ON users_shopspy FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Allow email check for registration" ON users_shopspy FOR SELECT TO anon USING (true);
CREATE POLICY "Service role full access users" ON users_shopspy FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access admins" ON admins_shopspy FOR ALL TO service_role USING (true);
CREATE POLICY "Service role full access logs" ON webhook_logs_shopspy FOR ALL TO service_role USING (true);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_updated_at
  BEFORE UPDATE ON users_shopspy
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Admin padrão
INSERT INTO admins_shopspy (email, name)
VALUES ('shopspyadmin@gmail.com', 'Admin ShopSpy')
ON CONFLICT (email) DO NOTHING;
